### ISSUE TITLE
Erro on running App.java

### ISSUE THREAD

**Issue by Nicholas-Barbosa** [microsoftgraph/msgraph-training-java#15]
Hi, When I run App.java, I receive this erro:
```
 Exception in thread "main" java.lang.NoClassDefFoundError: com/nimbusds/oauth2/sdk/auth/ClientAuthentication
	at graph.Authentication.getUserAccessToken(Authentication.java:45)
	at graph.App.main(App.java:39)
Caused by: java.lang.ClassNotFoundException: com.nimbusds.oauth2.sdk.auth.ClientAuthentication
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 2 more
```
I added all the JARs to my project.

-microsoft-graph-1.8.0.jar
-msal4j-1.6.1.jar
-slf4j-nop-1.8.0-beta4.jar

What should be the problem, or missing?Thanks!!

**Comment by jasonjoh** [comment]
That's a dependency of msal4j, so Gradle should have pulled that down for you. There may be an issue with how your classpath is configured. What do you get if you run `.\gradlew dependencies` in your project directory? How about `.\gradlew clean` or `.\gradlew build`?

**Comment by Nicholas-Barbosa** [comment]
Its works!! But, can I download or open files from oneDrive or oneDrive for Buisiness?

**Comment by jasonjoh** [comment]
Not with this sample as it is, it doesn't do any of that. You'd need to add code yourself and update the permissions scopes in the sample for the required Files scopes. See https://docs.microsoft.com/en-us/graph/api/driveitem-get-content?view=graph-rest-1.0&tabs=java
